### ISSUE TITLE
Suggestion: Make the "values" in manifest.yml Optional

### ISSUE THREAD

**Issue by kevingzhang** [wascc/wascc-host#29]
Ref: https://github.com/wascc/wascc-host/commit/fda513cca94fb3a6b875c8ba4d7ca0ee20e8fcae#r38759604

If an actor binding doesn't need a config when bind_actor() using manifest.yaml, a "values" has to be added into the yaml file, otherwise there would be a runtime error. 
apply_manifest is looking for the "values" field to generate a HashMap even it is not actually needed.

I would suggest to change it to Optional. Thanks

**Comment by autodidaddict** [comment]
Do you mean a scenario where an actor needs to be bound to a provider with no data? I can't think of a use case for that off hand.

If an actor doesn't need configuration data for a provider, then the binding itself is optional - you don't need a binding entry in the manifest or a call to bind_actor.

Can you describe the use case where you've got an actor that needs a binding but doesn't need configuration values?

**Comment by kevingzhang** [comment]
I write my own provider. The provider doesn't need config so far, but it needs a binding_name for multiple instances case.

**Comment by autodidaddict** [comment]
Ah okay that makes sense. I'll get that into master soon.

**Comment by kevingzhang** [comment]
thank you very much. One more question, not related to this issue. How do an actor instance know its unique ID, such as [Guest 2]. I can see [Guest 2] in wapc log, but I do not know if it is available inside the actor. Or, there is another ID for different actor instances.

**Comment by autodidaddict** [comment]
Inside the actor, it should not know its own ID because that can change
depending on the keys and how the actor is signed.

Capability providers are given the actor unique IDs. If you want to give an
actor information at runtime, you can actually call OP_BIND_ACTOR on the
actor from the host. The Gantry catalog actor does this to accept the ID of
a root operator.

If you want to dial into the community meeting this week we can chat about
your use case and see if there's a way we can handle it better.

**Comment by autodidaddict** [comment]
waPC uses numbers for guest modules. waSCC uses the subject key of the
embedded security token.

**Comment by kevingzhang** [comment]
Thank you very much Kevin. Your answer is very helpful. I would like to join the chat some day, not sure this week or later. Wascc is an awesome product.
