### ISSUE TITLE
Multiple calls to `NativeCapability::from_file` fails with logger error

### ISSUE THREAD

**Issue by rylev** [wascc/wascc-host#3]
I've reduced this error down to the following code:

```rust
const HTTP_LIB: &str = "./lib/libwascc_httpsrv.dylib";
#[test]
fn call_should_be_itempotent() {
  NativeCapability::from_file(HTTP_LIB);
  NativeCapability::from_file(HTTP_LIB);
}
```

This fails with the following error:

```
thread '<unnamed>' panicked at 'env_logger::init should not be called after logger initialized: SetLoggerError(())', src/libcore/result.rs:1165:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: wascc_host::capability::NativeCapability::from_file
             at /Users/ryanlevick/.cargo/registry/src/github.com-1ecc6299db9ec823/wascc-host-0.1.5/src/capability.rs:43
  16: wok::wasm::wascc::test::call_should_be_itempotent
             at src/wasm/wascc.rs:54
  17: wok::wasm::wascc::test::call_should_be_itempotent::{{closure}}
             at src/wasm/wascc.rs:52
  18: core::ops::function::FnOnce::call_once
             at /rustc/eb3f7c2d3aec576f47eba854cfbd3c1187b8a2a0/src/libcore/ops/function.rs:232
  19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eb3f7c2d3aec576f47eba854cfbd3c1187b8a2a0/src/liballoc/boxed.rs:1022
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  21: std::panicking::try
             at /rustc/eb3f7c2d3aec576f47eba854cfbd3c1187b8a2a0/src/libstd/panicking.rs:270
  22: std::panic::catch_unwind
             at /rustc/eb3f7c2d3aec576f47eba854cfbd3c1187b8a2a0/src/libstd/panic.rs:394
  23: test::run_test_in_process
             at src/libtest/lib.rs:567
  24: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:474
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test wasm::wascc::test::call_should_be_itempotent ... FAILED
```

Obviously calling this function twice in a row doesn't make a ton of sense but I first noticed this when a failure was happening with two tests running in parallel. I however could not find anywhere in my code or wascc-host that actually sets a logger.

**Comment by autodidaddict** [comment]
:thinking: there are still a few global statics lying around in the codebase that haven't yet been migrated out, I suspect one of them might be to blame. I'll take a look at the code and see if anything sticks out.

Thanks for reporting this.

**Comment by autodidaddict** [comment]
If you look at the code in the HTTP library, the plugin struct's `default` function (used by the `new` function) is calling `env_logger::init`. So what's actually happening is the HTTP server is having its constructor called twice, and `env_logger` throws a panic if it's called twice.

@rylev it's definitely an issue with the same module calling init logger twice. There's a different version of init, `try_init` that won't panic if there's already an initialized global logger. I can't guarantee that the libraries will be stable when running multiple copies of the same one, but it shouldn't panic because of the logger.

**Comment by autodidaddict** [comment]
As for testing, it might be safer for testing the host process (which is based on the assumption of being the only host in memory) to force acceptance-type tests to run in sequence rather than parallel. Or, rather than building multiple hosts, you could build a single host that is available throughout your test suite.

**Comment by autodidaddict** [comment]
Fixed in master for the HTTP server.
