### ISSUE TITLE
How to do asynchronous communication in lattice mode

### ISSUE THREAD

**Issue by amar123deep** [wascc/wascc-host#71]
Currently one can only do synchronous communication using [`call` function](https://github.com/wascc/wascc-actor/blob/master/src/untyped.rs#L47). I was wondering if there is plan to provide asynchronous call feature. The use-case could be chain of actors's call such as `A--> B --> C --> D ....--> Z`. Actor `A` will be blocked till actor `Z` returns in case of a synchronous call.

**Comment by autodidaddict** [comment]
There's a couple of types of functionality illustrated at the same time with your example. If A is blocked, and its an actor, then this is a _synchronous_ call. Actors are single-threaded and as a result they cannot spawn a child thread or execution worker of any kind and asynchronously wait for work to complete. These synchronous calls also keep the actor's inbound work queue from moving. If A makes an _asynchronous_ `cast` to B, then A can safely return to idle state and await an incoming message from anywhere, which could be a direct invocation from actor Z, or simply a message published to a topic, etc. But user code will _not_ appear to be synchronous - you won't be able to have code that looks like `await call(B)`

I do have plans for an asynchronous actor call function, described here in this newly created issue - #72 

So, while asynchronous calls are planned, they may not necessarily be what you're looking for in order to support a chain of blocking calls.

**Comment by amar123deep** [comment]
Thanks! I was looking for the `async call` feature. Actor `A` can do some other useful tasks while waiting for the response.

**Comment by autodidaddict** [comment]
Yep, then you'll want to watch #72
