### ISSUE TITLE
ways to update binding to the wascc-host

### ISSUE THREAD

**Issue by amar123deep** [wascc/wascc-host#76]
Is there a way to update binding to the wascc-host without restarting it? For example, one case could be to subscribe to a new [topic](https://github.com/wascc/wascc-host/blob/master/examples/subscriber.rs#L32). In case there is way to dynamically reset the topic, then we don't need to restart the host, but just update the host with a new manifest file.

**Comment by autodidaddict** [comment]
There is currently no way to modify an existing binding. I'm very wary of enabling this kind of behavior. I am a huge proponent of the idea of the immutable production environment, because a mutable one can, by definition, be mutated by malicious actors. If you could change a binding at runtime without being either the actor or the provider in that scenario, then you could potentially perform all kinds of attacks.

So to implement something like this, we'd have to find a way to secure the "modify binding" operation such that it can only be performed by a suitably authorized entity... and waSCC doesn't currently have the concept of superusers/admins/etc.

I'll do some more thinking on this

**Comment by autodidaddict** [comment]
I think for now, at least until I can find a concrete use case that requires this, I'm going to avoid allowing in-place modification of bindings because it's a security risk. The workaround for now is to remove the old binding and replace it with the new one containing the new values.
